---
include:
  - board: seeeduino_xiao_ble
    shield: ec-test_r rgbled_adapter
    snippet: studio-rpc-usb-uart
  - board: seeeduino_xiao_ble
    shield: ec-test_l rgbled_adapter
  - board: seeeduino_xiao_ble
    shield: settings_reset